version: '3.8'

services:
  php:
    platform: linux/amd64
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  web:
    platform: linux/amd64
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
